---
- hosts: all
  become: true
  gather_facts: yes
  vars:
   user_name: aman
   group_name: devops
  vars_files:
   - Variable.yml
  
  tasks:
    - name: Check the time
      command: date
    - name: create user serge
      user:
         name: "{{user_name}}"
         comment: Serge Admin
    - name: create group
      group:
         name: "{{group_name}}"
         state: present
    - name: Install package
      package:
        name: "{{pkg_name}}"
        state: present  